### ISSUE TITLE
The Repository structure is not as required

### ISSUE THREAD

**Issue by pushpdeep** [Shreyas-Mishra/Blockchain#1]
The repo is quite good, but still the structure needs to be modified. 

Please see this below.

Please refer this structure here and correct it ASAP.

the repository structure -
http://vlabs.iitb.ac.in/gitlab/Community-Docs/New-Lab-development/Round-templates

Documentation on porting of the experiment -
https://docs.google.com/document/d/1y8M1qslLjtyHmGnjclJQVEscNnB2n2JJTpeIADiuSkk/edit?usp=sharing
@Shreyas-Mishra

**Comment by Shreyas-Mishra** [comment]
Thankyou for accepting our application Sir.
We have made all the required changes kindly see to it if any further
change is to be made

https://github.com/Shreyas-Mishra/Blockchain

Looking forward to an early and positive reply.
Thank you

**Comment by Shreyas-Mishra** [comment]
Sir may I ask what does closing the conversation mean?
Like it's good or is something not?

**Comment by Shreyas-Mishra** [comment]
Sir now that the issue has been resolved when can we accept the link for
payment for the same ?

**Comment by pushpdeep** [comment]
yes. go ahead

*---Pushpdeep.Mishra*

**Comment by Shreyas-Mishra** [comment]
sir where can i get the payment link?
